services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - s3
    environment:
      - S3_ENDPOINT=http://s3:9000
      - S3_ACCESS_KEY=TF4QBBMadLeEiAm
      - S3_SECRET_KEY=k9uVR3K1LvUR66z
      - S3_BUCKET_NAME=dummy-data
      - APP_PORT=8080
      - DUMMY_DATA=yes

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=TF4QBBMadLeEiAm
      - MINIO_SECRET_KEY=k9uVR3K1LvUR66z
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  minio_data: